#!/bin/sh
ssh -i root@223.130.133.132 <<EOF
	export BUILD_ID=dontKillMe
    
    cd ~/Cornstory-node
    git pull origin master
    curl -o-   https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh    | bash
    . ~/.nvm/nvm.sh 
    nvm install 17.9.1 
    npm install 
    npm install -g pm2
    pm2 restart ecosystem.config.js
EOF