#!/bin/sh
ssh -o StrictHostKeyChecking=no cornstory@101.79.8.55 "command" <<EOF	
    cd ~/Cornstory-node
    git pull origin master
    curl -o-   https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh    | bash
    . ~/.nvm/nvm.sh 
    nvm install 17.9.1	//젠킨스에서 설정한 node 버전
    npm install
    npm install -g pm2
    pm2 restart ecosystem.config.js
    exit
EOF